# Exercise file for numpy

In [1]:
lst = [1, 2, 3, 4, 5]

In [2]:
lst

[1, 2, 3, 4, 5]

In [3]:
import numpy as np

In [8]:
a=np.array(lst)

In [9]:
a

array([1, 2, 3, 4, 5])

In [10]:
lst=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [11]:
np.array(lst)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
np.arange(2,4,0.25)

array([2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75])

In [17]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

get a matrix of all ones -3x4

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.linspace(0,5,15)

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

In [24]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [25]:
np.random.rand(5,5)

array([[0.16134683, 0.81039104, 0.64804177, 0.81864526, 0.33056599],
       [0.08182134, 0.75518486, 0.52918018, 0.61010991, 0.29133243],
       [0.99357654, 0.16780417, 0.91898958, 0.73022416, 0.75417512],
       [0.64967427, 0.8398151 , 0.99990146, 0.35820715, 0.3862889 ],
       [0.92963016, 0.55348806, 0.6596968 , 0.7930955 , 0.8969919 ]])

In [28]:
np.random.randn(6,4)

array([[-1.13799456, -0.67799602, -0.83205506,  1.98889023],
       [ 0.15773235,  0.72811379, -0.05471305, -1.2180819 ],
       [ 0.11571758, -1.39425631,  0.12817769,  1.08991982],
       [ 1.10137326,  1.53983746, -0.3941189 , -0.22662746],
       [ 0.50694087,  0.13222577,  0.56183921, -0.05013732],
       [-1.12766564,  0.02000488,  1.01744524, -0.12364035]])

In [30]:
np.random.randint(1,50)

43

In [36]:
tst=np.arange(24)

In [37]:
tst

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [48]:
tst.reshape(8,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])