# Conditional returns

In [2]:
import numpy as np

In [3]:
a=np.arange(2,20)

In [4]:
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [5]:
a>10

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [6]:
b=a[a<10]

In [7]:
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
b[:]=37

In [9]:
b

array([37, 37, 37, 37, 37, 37, 37, 37])

In [10]:
a*2

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
       38])

In [12]:
a**3

array([   8,   27,   64,  125,  216,  343,  512,  729, 1000, 1331, 1728,
       2197, 2744, 3375, 4096, 4913, 5832, 6859], dtype=int32)

In [13]:
a+a

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
       38])

In [14]:
a*a

array([  4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169, 196,
       225, 256, 289, 324, 361])

In [15]:
np.sqrt(a)

array([1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974,
       2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479,
       3.46410162, 3.60555128, 3.74165739, 3.87298335, 4.        ,
       4.12310563, 4.24264069, 4.35889894])