# Intermediate stuff with numpy

In [1]:
import numpy as np

In [2]:
a=np.arange(10,21)

In [3]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
a[4]

14

In [5]:
a[2:6]

array([12, 13, 14, 15])

In [15]:
b=a[5:]

In [9]:
b

array([15, 16, 17, 18, 19, 20])

In [24]:
b[1:4]=6

In [25]:
b

array([6, 6, 6, 6, 6, 6])

In [26]:
a

array([10, 11, 12, 13, 14,  6,  6,  6,  6,  6,  6])

In [27]:
b=[1,2,3,4,5,6,7,8]

In [33]:
b=np.array(b)

In [34]:
b

array([1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
b[:]=45

In [60]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [61]:
c=a[4:8]

In [62]:
c[:]=45

In [63]:
c

array([45, 45, 45, 45])

In [64]:
a

array([ 0,  1,  2,  3, 45, 45, 45, 45,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])