# for 2d arrays numpy

In [1]:
import numpy as np

In [10]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
a[:2,:2]

array([[1, 2],
       [4, 5]])

In [13]:
a[1:,:2]

array([[4, 5],
       [7, 8]])

In [14]:
a[1:,1:]

array([[5, 6],
       [8, 9]])